#!/usr/bin/env python3
"""Teste das melhorias na detecção de títulos"""

import sys
import os
from pathlib import Path

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from converter.steps.markdown_conversion_step import MarkdownConversionStep

def test_title_detection():
    """Testa a detecção de títulos com exemplos problemáticos"""
    step = MarkdownConversionStep()
    
    # Exemplos problemáticos identificados nos arquivos
    problematic_examples = [
        "do",
        "da", 
        "de",
        "Davi",
        "Saul",
        "Daniel",
        "Ezequiel",
        "Jeremias",
        "Exilados",
        "Esdras",
        "Neemias",
        "Zorobabel",
        "anos",
        "Bill Jones",
        "Queda",
        "OPBSG",
        "Number Three Occasional Papers",
        "Baraminology Study Group",
        "All Rights Reserved",
        "Cronologia Bíblica",
        "O que vamos estudar hoje",
        "Qual o principal",
        "Montando o quebra cabeça",
        "Ordens dadas por Deus",
        "Tentação (def.):",
        "O desejo de satisfazer",
        "Ouvindo o homem",
        "passos do Senhor Deus",
        "jardim quando soprava",
        "dia",
        "Quando soprava a brisa",
        "entardecer, o homem",
        "ouviram o SENHOR Deus",
        "pelo jardim e se esconderam",
        "A aliança Adâmica:",
        "Farei que haja inimizade",
        "entre você e a mulher",
        "entre a sua descendência",
        "o descendente",
        "Creationism",
        "this volume",
        "of Proceedings of the International",
        "Conference on creation",
        "Recommended Citation",
        "Chaffin, Eugene F.",
        "Available at:",
        "ACCELERATED DECAY: THEORETICAL MODELS",
        "EUGENE F. CHAFFIN",
        "405 Tebblewood Dr.",
        "Simpsonville, SC 29680",
        "Physics Professor, Bob Jones University",
        "KEYWORDS :",
        "Accelerated decay, Age of the Earth",
        "Tunneling, Beta Decay, Alpha decay",
        "understandings of mathematics",
        "physics have enabled reasons",
        "explanations to be given in",
        "particle physics which had not",
        "been previously possible",
        "accelerated",
        "radioactive decay, which is",
        "the study of the possibility",
        "radioactive half-lives had",
        "smaller magnitudes earlier",
        "in history than today",
        "have remained constant over",
        "the history of the universe",
        "are found in great quantity",
        "in recent physics literature",
        "we will discuss some ideas",
        "about multidimensional topology",
        "and how this relates to",
        "the quantities in physics",
        "which most directly determine",
        "decay rates, the so-called",
        '"coupling constants."',
        "ALPHA DECAY AND VARIATION",
        "OF THE NUCLEAR FORCE STRENGTH",
        "Figure 1. The Square-Well Potential",
        "with Coulomb Barrier",
        "Historically, the numerical",
        "treatment of alpha decay has",
        "relied on quantum mechanics",
        "and the tunneling theory",
        "Figure 1 shows the usual",
        "scheme were the potential",
        "felt by an alpha particle",
        "is modeled by a square well",
        "for the interior of the nucleus",
        "and a Coulomb repulsion outside",
        "Classically, a particle could",
        "not occupy region II of the",
        "figure; thus it could not have",
        "the negative energy that would",
        "be required for it to have",
        "only a few MeV of kinetic",
        "energy when it escapes to infinity",
        "However, a wave such as that",
        "used in quantum theory can leak",
        "through, even though the particle",
        "would have a negative energy for",
        "radius less than the",
        "r value shown in the figure",
        "E",
        "Although the changes in physical",
        '"constants" suggested in recent',
        "physics literature are very small",
        "alpha decay rates are very",
        "sensitive to small changes in",
        "well depths or shapes",
        "At the 1994 International",
        "Conference on creation",
        "Chaffin [12] discussed result",
        "of a numerical study, using a",
        "simple computer program, which",
        "allowed the depth of the nuclear",
        "potential well to vary",
        "The radius of the",
        "nucleus and the depth of the",
        "potential well represent two",
        "variables which are tied to",
        "the energy of the",
        "α",
        "emitted",
        "-particle and the decay constant",
        "In this simple model a constraint",
        "is needed, which may be",
        "α",
        "take to be the approximate",
        "constancy of radioactive halo",
        "radii [11, 22, 30, 44]",
        "If the energy of the",
        "-particle is held constant",
        "then the halo radius will",
        "also be constant",
        "science the radius of a halo",
        "ring is slightly dependent on",
        "the dose of radiation and the",
        "size of the halo inclusions",
        "an exact constraint on the",
        "α",
        "α",
        "-particle energy cannot be",
        "maintained",
        "For a 5 MeV change in the",
        "potential well depth, with the",
        "α",
        "-energy held exactly constant",
        "the computer program showed",
        "that the decay constant will",
        "change by only",
        "one power of ten",
        "If the",
        "α",
        "-energy is allowed to change",
        "by 10% or so, then the decay",
        "constant changes",
        "5",
        "by about 10",
        "If the accelerated decay",
        "needed to explain the data is",
        "restricted to about one year",
        "or so, then a change in the",
        "decay constant of",
        "9",
        "or so may be required",
        "Thus these considerations",
        "seemed to indicate that a",
        "one-year episode of accelerated",
        "decay at the time of the Flood",
        "may not be enough",
        "To test the variability of the",
        "decay constant, the computer",
        "program mentioned above, which",
        "was a Fortran program, was",
        "rewritten using",
        "Mathematica",
        "a very powerful, modern",
        "software package which",
        "facilitates numerical work of",
        "this sort",
        "For the square well potential",
        "on the inside of the nucleus",
        "the",
        "Mathematica",
        "notebook gave essentially",
        "the same answers as the",
        "earlier work",
        "In collaboration with Gothard",
        "and Tuttle [9], Chaffin",
        "modified the notebook to use a",
        "harmonic oscillator potential",
        "for the interior region, were",
        "the nuclear potential is felt",
        "by the alpha particle",
        "In the course of this work",
        "it was discovered that, as the",
        "nuclear potential well depth",
        "is changed, and the nuclear",
        "radius changes slightly, it is",
        "possible to have a sudden",
        "change in the number of nodes",
        "of the real part of the alpha",
        "particle's",
        "4",
        "wavefunction",
        "This was modeled for both the",
        "harmonic oscillator and square",
        "well potentials, with nearly",
        "the same result for either",
        "notebook",
        "Figure 2. Sudden change in the",
        "number of nodes",
        "The harmonic oscillator wave",
        "function for well depths",
        "ρ",
        "η",
        "ρ",
        "of 58 MeV (a) and 54 MeV (b)",
        "The x-axis is the radial",
        "coordinate of the alpha particle",
        "T= /(2 ), were",
        "η",
        "are defined in Green and Lee",
        "[26]",
        "Figure 2a shows the harmonic",
        "oscillator wave function for a",
        "well depth of 58 MeV",
        "Figure 2b shows what happens",
        "when the well depth is changed",
        "to 54 MeV, without changing",
        "the alpha particle energy",
        "If one counts the number of",
        "nodes in Figure 2a, there are",
        "nine, not counting the ones at",
        "zero and infinity",
        "For Figure 2b, there are eight",
        "nodes, a reduction by one",
        "Figure 3. The decay constant",
        "versus well depth for the",
        "harmonic oscillator interior",
        "potential",
        "The graph shows a",
        "discontinuity, which occurs",
        "when the wavefunction changes",
        "the number of nodes as the",
        "radius slowly increases",
        "The change in the number of",
        "nodes causes the probability",
        "of tunneling to change by",
        "about a factor of",
        "ten, as shown by the",
        "discontinuity in the graph of",
        "Figure 3",
        "Tunneling probabilities depend",
        "on the size of the wavefunction",
        "at infinity",
        "The two graphs of Figure 2a,b",
        "show the wavefunction decreasing",
        "to zero at",
        "5",
        "infinity",
        "However, the probability of",
        "alpha decay for a nucleus such",
        "as uranium-238 is very low",
        "hence the wavefunction will",
        "have small oscillation of both",
        "its real and imaginary parts",
        "too small to show on this scale",
        "Figure 4 shows a plot of the",
        "real part of the wavefunction",
        "for well depth parameter of 54",
        "done with Mathematica",
        "The x-axis shows a dimensionless",
        "variable T (defined in [21])",
        "whose size represents the",
        "distance from the nucleus",
        "Figure 4: The real part of the",
        "Coulombic wavefunction outside",
        "the Coulomb barrier",
        "The oscillatory behavior shows",
        "that the probability of escape",
        "is not zero for the alpha",
        "particle",
        "The x-axis is the",
        "ρ",
        "dimensionless radial coordinate",
        "defined in Green and Lee [26]",
        "The use of potentials with a",
        "sharp boundary between the",
        "interior and exterior of the",
        "nucleus is not",
        "realistic",
        "Consequently, In collaboration",
        "with Daniel Banks [7], a",
        "Mathematica",
        "notebook was written to",
        "use the exponentially diffuse",
        "boundary square well",
        "for the interior of the nucleus",
        "This interior potential was",
        "originally investigated in a",
        "classic work by Green and Lee",
        "[26], although they did not",
        "apply it to alpha decay",
        "Figure 5 shows the potential",
        "well and the corresponding",
        "wavefunction for this case",
        "Figure 5: The Exponentially",
        "Diffuse boundary potential and",
        "the corresponding wavefunction",
        "The vertical",
        "ρ",
        "axis is energy in MeV and the",
        "horizontal axis is the radius",
        "For the wavefunction, the",
        "vertical axis is the real part",
        "of the wavefunction multiplied",
        "by ten",
        "The use of this potential",
        "allows the potential energy to",
        "increase gradually as the",
        "distance increases"
    ]
    
    # Exemplos de títulos válidos para comparação
    valid_titles = [
        "Abstract",
        "Introduction", 
        "Methods",
        "Results",
        "Discussion",
        "Conclusion",
        "References",
        "Bibliography",
        "Appendix",
        "1. Introduction",
        "2. Methods and Materials",
        "3. Results and Analysis",
        "4. Discussion",
        "5. Conclusion",
        "A Refined Baramin Concept",
        "Accelerated Decay: Theoretical Models",
        "Catastrophic Plate Tectonics",
        "Biostratigraphic Continuity and Earth History",
        "The Genesis Flood",
        "Creationist concepts of biology",
        "The criticism of the baramin",
        "The Genesis Flood Based on citations",
        "Quantum mechanical calculations",
        "Alpha Decay and Variation of the Nuclear Force Strength"
    ]
    
    print("🔍 TESTE DE DETECÇÃO DE TÍTULOS MELHORADA")
    print("=" * 60)
    
    print("\n❌ PROBLEMÁTICOS (devem ser FALSO):")
    print("-" * 40)
    problematic_count = 0
    for example in problematic_examples:
        is_title = step._is_title(example)
        status = "❌ FALSO" if not is_title else "⚠️  PROBLEMA: marcado como título"
        print(f"{status}: '{example}'")
        if is_title:
            problematic_count += 1
    
    print(f"\n📊 Problemas encontrados: {problematic_count}/{len(problematic_examples)}")
    
    print("\n✅ VÁLIDOS (devem ser VERDADEIRO):")
    print("-" * 40)
    valid_count = 0
    for example in valid_titles:
        is_title = step._is_title(example)
        status = "✅ VERDADEIRO" if is_title else "❌ PROBLEMA: não marcado como título"
        print(f"{status}: '{example}'")
        if is_title:
            valid_count += 1
    
    print(f"\n📊 Títulos válidos detectados: {valid_count}/{len(valid_titles)}")
    
    print(f"\n🎯 RESULTADO GERAL:")
    print(f"   Problemas corrigidos: {len(problematic_examples) - problematic_count}/{len(problematic_examples)}")
    print(f"   Títulos válidos mantidos: {valid_count}/{len(valid_titles)}")
    
    if problematic_count == 0 and valid_count == len(valid_titles):
        print("🎉 PERFEITO! Todas as melhorias funcionaram corretamente!")
    else:
        print("⚠️  Ainda há problemas a serem corrigidos.")

if __name__ == "__main__":
    test_title_detection()
